### PR TITLE
Add support for Mutter

### PR DESCRIPTION
**Pull request by uhle**
[Mutter](https://gitlab.gnome.org/GNOME/mutter) is a pretty good alternative to any combinations of Metacity+Compton, Marco+Compton or Xfwm4+Compton. It is well supported and as the evolution of Metacity, it is the default window manager for GNOME 3. IMHO it seems to be more stable w.r.t. compositing than Compton and, thus, could be preferred.

### CODE REVIEW

**Comment by clefebvre** [comment]
Please don't modify .pot and help pages, they're generated.

**Comment by uhle** [comment]
`mintdesktop.pot`has not been manually changed but generated by `makepot`. I thought it would be good to have it in sync with recent changes. But sure, I can revert the content of `mintdesktop.pot` if you want me to.
Speaking of `wms.page`, the origin is `usr/share/help/C/mintdesktop/wms.page`, isn't it? I couldn't find any of those `mintdesktop.mo` according to `generate_desktop_files`. What am I missing if I want to provide translated descriptions for Mutter next to default C locale?

**Comment by clefebvre** [comment]
You shoudn't provide any translations at all. English msgids get sent to Launchpad and we bring them back here fully translated. In your PR there should be no translations at all.

**Comment by clefebvre** [comment]
We keep the pot outdated on purpose also. That's how we know whether LP is up to date or not.

**Comment by uhle** [comment]
Okay, I see. Do I get it right if I conclude that it's just allowed to change `usr/share/help/C/mintdesktop/wms.page` only?

**Comment by clefebvre** [comment]
Yes

**Pull request merged**
